#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""LENTE 2 — il secondo giro: le costanti GEMELLE, i tempi delle buste,
le due meta' e i cablaggi rimasti fuori dal primo giro."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import lente2 as L
C, K, G, RG, V, VS, LB = L.C, L.K, L.G, L.RG, L.V, L.VS, L.L

L.MUT = [
# ------------------------------------------- LE COSTANTI GEMELLE (comment-only)
C(LB, "	if umore < -0.35:\n		return \"di malumore\"",
     "	if umore < -0.90:\n		return \"di malumore\"  # MUT",
     "GEMELLA umore·Limbico si stacca da Regia.CAPO_UMORE",
     "il commento dice «un test lo lega»: il test confronta col LETTERALE"),
K(G, "CODA_VITA", "7.87", "1.00", "GEMELLA CODA_VITA·derivata a mano da tau/soglia"),
K(G, "PUNTO_MOLLE", "4.0", "40.0", "GEMELLA PUNTO_MOLLE (= Visitor.TESTA_TORNA)"),
K(G, "PUNTO_DECISA", "9.0", "4.0", "GEMELLA PUNTO_DECISA (= Visitor.TESTA_VAI)"),
K(G, "CAPO_K", "170.0", "40.0", "GEMELLA CAPO_K (= FaceController)"),
# ------------------------------------------------ I TEMPI DELLE BUSTE
K(G, "PUNTO_SPINTA_DUR", "0.8", "0.05", "TEMPO punto·spinta lampo"),
K(G, "RACCOLTO_ATTACCO", "2.6", "25.0", "TEMPO raccolto·attacco a scatto"),
K(G, "RACCOLTO_RILASCIO", "1.65", "12.0", "TEMPO raccolto·rilascio piu' veloce dell'attacco",
  "«da una rinuncia si esce PIANO»"),
K(G, "RACCOLTO_TENUTA", "2.0", "0.2", "TEMPO raccolto·tenuta 0,2 s"),
K(G, "RIALZO_DUR", "1.6", "0.25", "TEMPO rialzo·durata 0,25 s"),
K(G, "LARGO_DUR", "3.0", "0.4", "TEMPO largo·durata 0,4 s"),
K(G, "LARGO_DIP_SU", "0.15", "1.20", "TEMPO largo·esitazione che non arriva mai"),
K(G, "LARGO_DIP_GIU", "0.20", "2.00", "TEMPO largo·esitazione che non passa piu'"),
# ------------------------------------------------ LE DUE META'
K(G, "RACCOLTO_EAR_DX", "0.06", "0.0", "META' raccolto·orecchie stessa quota"),
K(G, "RACCOLTO_AX_DX", "0.23", "0.30", "META' raccolto·braccia stessa quota"),
K(G, "RACCOLTO_MEZZA_RIT", "0.07", "0.0", "META' raccolto·orecchio senza ritardo"),
K(G, "RACCOLTO_MEZZA_PIGRO", "0.62", "1.0", "META' raccolto·orecchio non pigro"),
K(G, "RACCOLTO_MEZZA_MOLLA", "1.30", "1.0", "META' raccolto·orecchio molla insieme"),
K(G, "RACCOLTO_BRACCIO_PIGRO", "0.70", "1.0", "META' raccolto·braccio non pigro"),
K(G, "LARGO_EAR_DX", "0.05", "0.0", "META' largo·orecchie stessa quota"),
K(G, "LARGO_AX_DX", "0.085", "0.12", "META' largo·braccia stessa quota"),
K(G, "LARGO_MEZZA_RIT", "0.08", "0.0", "META' largo·senza ritardo"),
K(G, "LARGO_MEZZA_PIGRO", "0.66", "1.0", "META' largo·senza pigrizia"),
K(G, "CODA_MEZZA_TAU", "2.55", "2.80", "META' coda·stesso tau (un filo solo)"),
K(G, "CODA_EAR_DX", "0.50", "0.45", "META' coda·orecchie stessa quota"),
K(G, "CODA_AX_DX", "0.245", "0.30", "META' coda·braccia stessa quota"),
K(G, "LARGO_TREM", "0.006", "0.0", "FORMA largo·tremolio 0"),
K(G, "RACCOLTO_AX_TREM", "0.006", "0.0", "FORMA raccolto·tremolio braccia 0"),
# ------------------------------------------------ LA GRAMMATICA
C(G, '	"pensiero": {"g": "punto", "d": {"decisa": true, "capo": true}},',
     '	"pensiero": {"g": "punto", "d": {"decisa": true}},  # MUT',
     "GRAM pensiero·senza il Capo"),
C(G, '	"rinuncia": {"g": "raccolto", "d": {"rialzo": 0.6}},',
     '	"rinuncia": {"g": "raccolto", "d": {}},  # MUT',
     "GRAM rinuncia·non si esce col mezzo respiro"),
C(G, '	"premessa": {"g": "punto", "d": {}},',
     '	"premessa": {"g": "raccolto", "d": {}},  # MUT',
     "GRAM premessa·diventa un Raccolto"),
# ------------------------------------------------ VISITOR: le reti e i tempi
K(V, "FIATO_ETA", "0.55", "0.05", "VALV fiato·tutti anziani (nessun Punto frena)"),
C(V, "	# viaggio dopo, invisibile perché nessun test guarda la velocità.\n	gesto_spegni()",
     "	# viaggio dopo, invisibile perché nessun test guarda la velocità.\n	pass  # MUT",
     "RETE _enter_state·senza gesto_spegni()"),
C(V, "	# prestito la scala di un `_corpo` che sta per non esistere più.)\n	gesto_spegni(true)",
     "	# prestito la scala di un `_corpo` che sta per non esistere più.)\n	pass  # MUT",
     "RETE _monta_corpo·senza gesto_spegni(true)"),
C(V, "	# e poi si riscrive: nessun ordine da ricordare, nessuna base che invecchia.\n	gesto_spegni(true)",
     "	# e poi si riscrive: nessun ordine da ricordare, nessuna base che invecchia.\n	pass  # MUT",
     "RETE set_cucciolo·senza gesto_spegni(true)"),
C(V, "	# salto del rig nell'istante in cui la scena comincia.\n	gesto_spegni()",
     "	# salto del rig nell'istante in cui la scena comincia.\n	pass  # MUT",
     "RETE apri_scena·senza gesto_spegni()"),
C(V, "	# pensieri: sono un vicino che non sa camminare.\n	_gs_viaggio = false",
     "	# pensieri: sono un vicino che non sa camminare.\n	pass  # MUT",
     "RETE _walk_to·_gs_viaggio non si riarma (un Punto per PARTITA)"),
C(V, "	_gs_liv = move_toward(_gs_liv, mira, delta / rampa)",
     "	_gs_liv = mira  # MUT", "RETE livelli·nessuna rampa (24 gradi in un frame)"),
C(V, "	var gl := _gs_liv * _gs_liv * (3.0 - 2.0 * _gs_liv)",
     "	var gl := _gs_liv  # MUT", "RETE livelli·rampa lineare (spigolo di velocita')"),
C(V, "	if guadagno > 0.0 and _gs_capo_x != 0.0:\n		canali[\"hz\"] = float(canali[\"hz\"]) + _gs_capo_x * guadagno",
     "	if _gs_capo_x != 0.0:\n		canali[\"hz\"] = float(canali[\"hz\"]) + _gs_capo_x  # MUT",
     "RETE capo·il rollio ignora la rampa dei livelli"),
C(V, "	if not is_inside_tree():\n		return true\n	var reg := get_tree().get_first_node_in_group(\"visitors\")",
     "	if not is_inside_tree():\n		return false  # MUT\n	var reg := get_tree().get_first_node_in_group(\"visitors\")",
     "VALV capo_concesso·senza registro NEGA (degrado al contrario)"),
# ------------------------------------------------ VISITORS
K(VS, "CAPO_OGNI", "0.75", "60.0", "USH capo·si chiede una volta al minuto"),
K(VS, "ATTESA_RICONOSCIMENTO", "0.4", "5.0", "USH riconoscimento dopo 5 s"),
C(VS, "		_sussulto_cd[label] = 9.0",
      "		_sussulto_cd[label] = 0.5  # MUT",
      "USH riarmo del sussulto 0,5 s (la coda diventa monotona)",
      "«una coda deve decadere piu' in fretta del proprio riarmo»"),
C(VS, "		if d > 3.2:\n			continue",
      "		if d > 30.0:\n			continue  # MUT", "USH sussulto·raggio 30 m"),
C(RG, '"era_per_me": {"frase": "premessa", "attesa": 0.35},',
      '"era_per_me": {"frase": "premessa", "attesa": 1.00},',
      "REGIA era_per_me paga il periodo intero"),
C(RG, '"se_lo_tiene": {"frase": "pensiero", "attesa": 0.30},',
      '"se_lo_tiene": {"frase": "pensiero", "attesa": 1.00},',
      "REGIA se_lo_tiene paga il periodo intero"),
C(RG, '"si_e_trattenuto": {"frase": "rinuncia", "attesa": 0.45},',
      '"si_e_trattenuto": {"frase": "rinuncia", "attesa": 1.00},',
      "REGIA si_e_trattenuto paga il periodo intero"),
C(RG, '"quel_posto_no": {"frase": "evitamento", "attesa": 0.45},',
      '"quel_posto_no": {"frase": "evitamento", "attesa": 1.00},',
      "REGIA quel_posto_no paga il periodo intero"),
]

if __name__ == "__main__":
    sys.exit(L.main())
